version: '3.8'
services:

  frontend:
    image: "nginx:alpine"
 
    ports:
      - "80:80"
    volumes:
      - './front:/usr/share/nginx/html'

    networks:
      - frontend-net
      
  backend:
    build:
      context: ./backend
    ports:
      - "3001:3001"
    # environment:
    #   - PORT=3001
    #   - DATABASE_URL=postgresql://app:secret@database:5432/myapp

    env_file:
      - ./backend/.env

    healthcheck:
      test: ["CMD", "wget", "-q", "-O-", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 5

    networks:
      - backend-net
      - frontend-net
    depends_on:
      - database


    
  

  database:
    image: postgres
    restart: always


    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 30s
      timeout: 10s
      retries: 5
    
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=myapp
  
    volumes:
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
      -  postgres-data:/var/lib/postgresq
    networks:
      - backend-net
volumes:
  postgres-data:

networks:
  frontend-net:
  backend-net: