FROM golang:1.25 AS builder

WORKDIR /app

COPY main.go . 

RUN CGO_ENABLED=0 GOOS=linux go build -a -o server main.go



FROM alpine:latest
WORKDIR /app 
COPY --from=builder /app/server .

CMD ["./server"]
